=== dgunning/edgartools/data/13f/EDGAR Form 13F Schema Files/EDGAR Form 13F Schema Files/eis_13F_Filer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.sec.gov/edgar/thirteenffiler" xmlns:ns1="http://www.sec.gov/edgar/common" xmlns:ns2="http://www.sec.gov/edgar/statecodes" targetNamespace="http://www.sec.gov/edgar/thirteenffiler" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.sec.gov/edgar/common" schemaLocation="eis_Common.xsd"/>
	<xs:import namespace="http://www.sec.gov/edgar/statecodes" schemaLocation="eis_stateCodes.xsd"/>
	<xs:simpleType name="SUBMISSION_TYPE">
		<xs:annotation>
			<xs:documentation>
            Type of submission you are filing.  Choose a value from the appropriate family of
            Submission Types.  
            </xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="13F-HR"/>
			<xs:enumeration value="13F-HR/A"/>
			<xs:enumeration value="13F-CTR"/>
			<xs:enumeration value="13F-CTR/A"/>
			<xs:enumeration value="13F-NT"/>
			<xs:enumeration value="13F-NT/A"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PHONE_TYPE">
		<xs:annotation>
			<xs:documentation> Phone number of the contact person;maximum field size is 20 alphanumeric characters.  Hyphens may be included to improve readability.</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="20"/>
			<xs:pattern value="[a-zA-Z0-9\s#(),.\-]{1,20}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="FILER_CREDENTIALS">
		<xs:sequence>
			<xs:element name="cik" type="ns1:CIK_TYPE"/>
			<xs:element name="ccc" type="ns1:CCC_TYPE"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FILING_IDENTIFICATION">
		<xs:sequence>
			<xs:element name="credentials" type="FILER_CREDENTIALS"/>
			<xs:element name="fileNumber" type="ns1:FILE_NUMBER_TYPE" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="NOTIFICATION_TYPE">
		<xs:sequence>
			<xs:element name="notificationEmailAddress" type="ns1:INTERNET_ADDRESS_TYPE" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FLAG_TYPE">
		<xs:sequence>
			<xs:element name="confirmingCopyFlag" type="ns1:TRUE_FALSE_TYPE" minOccurs="0"/>
			<xs:element name="returnCopyFlag" type="ns1:TRUE_FALSE_TYPE" minOccurs="0"/>
			<xs:element name="overrideInternetFlag" type="ns1:TRUE_FALSE_TYPE" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CONTACT_TYPE">
		<xs:sequence>
			<xs:element name="contactName" type="ns1:NAME_TYPE"/>
			<xs:element name="contactPhoneNumber" type="PHONE_TYPE"/>
			<xs:element name="contactEmailAddress" type="ns1:INTERNET_ADDRESS_TYPE"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="INTEGER_NONNEGATIVE_3">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:totalDigits value="3" fixed="true"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="INTEGER_NONNEGATIVE_6">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:totalDigits value="6" fixed="true"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="INTEGER_NONNEGATIVE_16">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:totalDigits value="16" fixed="true"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CRD_NUMBER_TYPE">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{9}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AMENDMENT_TYPE">
		<xs:restriction base="xs:token">
			<xs:enumeration value="RESTATEMENT"/>
			<xs:enumeration value="NEW HOLDINGS"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="REASON_CONFIDENTIALITY">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Denied"/>
			<xs:enumeration value="Confidential Treatment Expired"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AMENDMENT_INFO">
		<xs:sequence>
			<xs:element name="amendmentType" type="AMENDMENT_TYPE"/>
			<xs:element name="confDeniedExpired" type="ns1:TRUE_FALSE_TYPE" minOccurs="0"/>
			<!-- if the above flag is true, then the following elements will be required for 13F-HR/A only-->
			<xs:element name="dateDeniedExpired" type="ns1:DATE_TYPE" minOccurs="0"/>
			<xs:element name="dateReported" type="ns1:DATE_TYPE" minOccurs="0"/>
			<xs:element name="reasonForNonConfidentiality" type="REASON_CONFIDENTIALITY" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FILING_MANAGER">
		<xs:sequence>
			<xs:element name="name" type="ns1:STRING_150_TYPE"/>
			<xs:element name="address" type="ns1:ADDRESS_TYPE"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="REPORT_TYPE">
		<xs:restriction base="xs:token">
			<xs:enumeration value="13F HOLDINGS REPORT"/>
			<xs:enumeration value="13F NOTICE"/>
			<xs:enumeration value="13F COMBINATION REPORT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="STRING_4000_TYPE">
		<xs:restriction base="xs:token">
			<xs:minLength value="1"/>
			<xs:maxLength value="4000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="OTHER_MANAGER">
		<xs:sequence>
			<xs:element name="cik" type="ns1:CIK_TYPE" minOccurs="0"/>
			<xs:element name="form13FFileNumber" type="ns1:FILE_NUMBER_TYPE" minOccurs="0"/>
			<xs:element name="crdNumber" type="CRD_NUMBER_TYPE" minOccurs="0"/>
			<xs:element name="secFileNumber" type="ns1:FILE_NUMBER_TYPE" minOccurs="0"/>
			<xs:element name="name" type="ns1:STRING_150_TYPE"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OTHER_MANAGER_2">
		<xs:sequence>
			<xs:element name="sequenceNumber" type="ns1:INTEGER_TYPE_3"/>
			<xs:element name="otherManager" type="OTHER_MANAGER"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OTHER_MANAGERS">
		<xs:sequence>
			<xs:element name="otherManager" type="OTHER_MANAGER" maxOccurs="100"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="OTHER_MANAGERS_2">
		<xs:sequence>
			<xs:element name="otherManager2" type="OTHER_MANAGER_2" maxOccurs="999"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SUMMARY_PAGE">
		<xs:sequence>
			<xs:element name="otherIncludedManagersCount" type="INTEGER_NONNEGATIVE_3" default="0"/>
			<xs:element name="tableEntryTotal" type="INTEGER_NONNEGATIVE_6" default="0"/>
			<xs:element name="tableValueTotal" type="INTEGER_NONNEGATIVE_16" default="0"/>
			<xs:element name="isConfidentialOmitted" type="ns1:TRUE_FALSE_TYPE" minOccurs="0"/>
			<xs:element name="otherManagers2Info" type="OTHER_MANAGERS_2" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="COVER_PAGE">
		<xs:sequence>
			<xs:element name="reportCalendarOrQuarter" type="ns1:DATE_TYPE"/>
			<xs:element name="isAmendment" type="ns1:TRUE_FALSE_TYPE" minOccurs="0"/>
			<xs:element name="amendmentNo" type="ns1:INTEGER_TYPE_2" minOccurs="0"/>
			<xs:element name="amendmentInfo" type="AMENDMENT_INFO" minOccurs="0"/>
			<xs:element name="filingManager" type="FILING_MANAGER"/>
			<xs:element name="reportType" type="REPORT_TYPE"/>
			<xs:element name="form13FFileNumber" type="ns1:FILE_NUMBER_TYPE" minOccurs="0"/>
			<xs:element name="crdNumber" type="CRD_NUMBER_TYPE" minOccurs="0"/>
			<xs:element name="secFileNumber" type="ns1:FILE_NUMBER_TYPE" minOccurs="0"/>
			<xs:element name="otherManagersInfo" type="OTHER_MANAGERS" minOccurs="0"/>
			<xs:element name="provideInfoForInstruction5" type="ns1:YES_NO_TYPE"/>
			<xs:element name="additionalInformation" type="STRING_4000_TYPE" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="SIGNATURE_BLOCK">
		<xs:sequence>
			<xs:element name="name" type="ns1:STRING_150_TYPE"/>
			<xs:element name="title" type="ns1:STRING_60_TYPE"/>
			<xs:element name="phone" type="PHONE_TYPE"/>
			<xs:element name="signature" type="ns1:STRING_150_TYPE"/>
			<xs:element name="city" type="ns1:STRING_30_TYPE"/>
			<xs:element name="stateOrCountry" type="ns2:STATE_COUNTRY_CODE"/>
			<xs:element name="signatureDate" type="ns1:DATE_TYPE"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FILER_INFO">
		<xs:sequence>
			<xs:element name="liveTestFlag" type="ns1:LIVE_TEST_TYPE"/>
			<xs:element name="denovoRequest" type="ns1:YES_NO_TYPE" minOccurs="0"/>
			<xs:element name="flags" type="FLAG_TYPE" minOccurs="0"/>
			<xs:element name="filer" type="FILING_IDENTIFICATION"/>
			<xs:element name="contact" type="CONTACT_TYPE" minOccurs="0"/>
			<xs:element name="notifications" type="NOTIFICATION_TYPE" minOccurs="0"/>
			<xs:element name="periodOfReport" type="ns1:DATE_TYPE"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEADER_DATA">
		<xs:sequence>
			<xs:element name="submissionType" type="SUBMISSION_TYPE"/>
			<xs:element name="filerInfo" type="FILER_INFO"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FORM_DATA">
		<xs:sequence>
			<xs:element name="coverPage" type="COVER_PAGE"/>
			<xs:element name="signatureBlock" type="SIGNATURE_BLOCK"/>
			<xs:element name="summaryPage" type="SUMMARY_PAGE" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="DOCUMENT_NAME_TYPE">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="32"/>
			<xs:pattern value="([a-zA-Z0-9]+[\w\._\-]*)([\.]([xXpP][mMdD][lLfF]))"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SUB_DOCUMENT_TYPE">
		<xs:restriction base="xs:token">
			<xs:enumeration value="INFORMATION TABLE"/>
			<xs:enumeration value="REQUEST LETTER"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="EDGAR_DOCUMENT_TYPE">
		<xs:sequence>
			<xs:element name="conformedName" type="DOCUMENT_NAME_TYPE"/>
			<xs:element name="conformedDocumentType" type="SUB_DOCUMENT_TYPE"/>
			<xs:element name="description" type="ns1:DOCUMENT_DESCRIPTION_TYPE" minOccurs="0"/>
			<xs:element name="contents" type="ns1:DOCUMENT_MIME_BLOCK_TYPE"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EDGAR_DOCUMENTS_TYPE">
		<xs:sequence>
			<xs:element name="document" type="EDGAR_DOCUMENT_TYPE" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="edgarSubmission">
		<xs:annotation>
			<xs:documentation>This is the root element for an Online submission.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="schemaVersion" type="ns1:SCHEMA_VERSION_TYPE" minOccurs="0"/>
				<xs:element name="headerData" type="HEADER_DATA"/>
				<xs:element name="formData" type="FORM_DATA"/>
				<xs:element name="documents" type="EDGAR_DOCUMENTS_TYPE" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dgunning/edgartools/tests/fixtures/13f/mfn-0000904454-26-000248/primary.xml
<?xml version="1.0" encoding="UTF-8"?>
<edgarSubmission xsi:schemaLocation="http://www.sec.gov/edgar/thirteenffiler eis_13F_Filer.xsd" xmlns="http://www.sec.gov/edgar/thirteenffiler" xmlns:ns1="http://www.sec.gov/edgar/common" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <schemaVersion>X0202</schemaVersion>
  <headerData>
    <submissionType>13F-HR/A</submissionType>
    <filerInfo>
      <liveTestFlag>LIVE</liveTestFlag>
      <flags>
        <confirmingCopyFlag>false</confirmingCopyFlag>
        <returnCopyFlag>false</returnCopyFlag>
        <overrideInternetFlag>false</overrideInternetFlag>
      </flags>
      <filer>
        <credentials>
          <cik>0001732811</cik>
          <ccc>XXXXXXXX</ccc>
        </credentials>
      </filer>
      <periodOfReport>12-31-2025</periodOfReport>
    </filerInfo>
  </headerData>
  <formData>
    <coverPage>
      <reportCalendarOrQuarter>12-31-2025</reportCalendarOrQuarter>
      <isAmendment>true</isAmendment>
      <amendmentNo>1</amendmentNo>
      <amendmentInfo>
        <amendmentType>NEW HOLDINGS</amendmentType>
        <confDeniedExpired>false</confDeniedExpired>
      </amendmentInfo>
      <filingManager>
        <name>MFN Partners Management, LP</name>
        <address>
          <ns1:street1>222 BERKELEY STREET, 13TH FLOOR</ns1:street1>
          <ns1:city>BOSTON</ns1:city>
          <ns1:stateOrCountry>MA</ns1:stateOrCountry>
          <ns1:zipCode>02116</ns1:zipCode>
        </address>
      </filingManager>
      <reportType>13F HOLDINGS REPORT</reportType>
      <form13FFileNumber>028-19231</form13FFileNumber>
      <crdNumber>000291755</crdNumber>
      <secFileNumber>801-112441</secFileNumber>
      <provideInfoForInstruction5>N</provideInfoForInstruction5>
    </coverPage>
    <signatureBlock>
      <name>Jon Reisman</name>
      <title>Chief Compliance Officer</title>
      <phone>617-443-2040</phone>
      <signature>/s/ Jon Reisman</signature>
      <city>Boston</city>
      <stateOrCountry>MA</stateOrCountry>
      <signatureDate>04-29-2026</signatureDate>
    </signatureBlock>
    <summaryPage>
      <otherIncludedManagersCount>0</otherIncludedManagersCount>
      <tableEntryTotal>2</tableEntryTotal>
      <tableValueTotal>24920000</tableValueTotal>
    </summaryPage>
  </formData>
</edgarSubmission>
